burp_suite/application/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from .forms import LoginForm, RegisterForm
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from .models import Admin
from . import db

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    
    if current_user.is_authenticated: #if the user is already signed in they can skip the login page
        return redirect(url_for('views.dashboard', username=current_user.username))

    if form.validate_on_submit():
        print(form.username.data, form.password.data)
        username = form.username.data
        password = form.password.data
        rememberMe = form.rememberMe.data

        admin = Admin.query.filter_by(username=username).first()
        if admin:
            if check_password_hash(admin.password, password):
                login_user(admin, remember=rememberMe)
                return redirect(url_for('views.dashboard', username=username))
            else:
                print("Incorrect password.")
                flash("Incorrect password.", category='passwordError')
        else:
            print("Username not found.")
            flash("Username not found.",category='usernameError')
    
    print("Login form errors:", form.errors)
    return render_template('auth/login.html', form=form)

@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        # print(form.firstName.data, form.lastName.data, form.username.data, form.password.data)
        firstName = form.firstName.data
        lastName = form.lastName.data
        username = form.username.data
        password = form.password.data
        rememberMe = form.rememberMe.data

        admin = Admin.query.filter_by(username=username).first()
        if admin:
            flash("Username already taken.")
        else:
            new_admin = Admin(firstName=firstName, lastName=lastName, username=username, password=generate_password_hash(password, method='scrypt'))
            db.session.add(new_admin)
            db.session.commit()
            login_user(new_admin,remember=rememberMe)
            return redirect(url_for('views.dashboard', username=username))

    print("Register form errors:", form.errors)
    return render_template('auth/register.html', form=form)

@auth.route("/logout")
@login_required #user must be logged in to access this route
def logout():
    name=str(current_user.firstName + " " + current_user.lastName)
    logout_user()
    return render_template('auth/logout.html', name=name)

burp_suite/application/views.py
from flask import Blueprint, render_template, url_for, redirect, Response, current_app
from flask_login import login_required, current_user
from datetime import datetime, time, date
from .forms import PositionForm, EmployeeForm, DepartmentForm, EventForm, EventFormEdit
from .models import Admin, Position, Employee, Department, CalendarDates
from . import db


views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template('index.html')

@views.route('/sitemap.xml', methods=['GET'])
def sitemap():
    pages = []
    # Static routes
    for rule in current_app.url_map.iter_rules():
        if "GET" in rule.methods and not rule.arguments:
            url = url_for(rule.endpoint, _external=True)
            pages.append(url)
    sitemap_xml = render_sitemap(pages)
    return Response(sitemap_xml, mimetype='application/xml')

def render_sitemap(pages):
    xml = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    # inject placehodler flag
    xml.append('<url><loc>https://flag/{SITEMAP_FLAG}</loc></url>')
    for page in pages:
        xml.append("  <url><loc>%s</loc></url>" % page)
    xml.append('</urlset>')
    return "\n".join(xml)

@login_required #user must be logged in to access the dashboard
@views.route('/<username>')
def dashboard(username):

    admin = Admin.query.filter_by(username=username).first()

    if admin:
        employees = Employee.query.filter_by(admin_id=admin.id).all()
        calendarEvents = CalendarDates.query.filter_by(admin_id=admin.id).all()
        departments = Department.query.filter_by(admin_id=admin.id).all()
        today = date.today()
        
        phoneNumbers = []#list of all the phone numbers
        birthdays = [] #list of all the birthdays
        totalEmployees = 0#total amount of employees and keeps count of iterations for phone numbers
        totalPayRole = 0
        largestDepartments = []#list to store the largest position(s)
        totalDepartments = 0
        employeesPerDepartment = 0

        for employee in employees:
            employeeBirthday = str(employee.birthday).split('-')
            brithdayMonth = int(employeeBirthday[1])
            brithdayDay = int(employeeBirthday[2])
            if brithdayMonth == today.month and brithdayDay == today.day:
                birthdays.append({
                    'name': employee.firstName + ' ' + employee.lastName,
                    'date': employee.birthday
                })
            #i only want to display 8 phone numbers
            if totalEmployees < 9:
                phoneNumbers.append({
                    'name': employee.firstName + ' ' + employee.lastName,
                    'phoneNumber': employee.phoneNumber
                })

            totalPayRole = totalPayRole + employee.salary
            totalEmployees += 1

        # randomDepartment = Department.query.filter_by(admin_id=admin.id).first()
        # if randomDepartment:
        #     max = randomDepartment.employeeCount #max is set to the employeeCount of a randomDepartment instead of 0. This way a department of 0 people wont be appended to the list and it will still work if all departments have 0 people                                    
        # else:
        #     max = 0
        max = 1
        for department in departments:       
            if department.employeeCount >= max:
                largestDepartments.append({
                    'title': department.title,
                    'employeeCount': department.employeeCount
                })
                max = department.employeeCount

            totalDepartments = totalDepartments + 1

        events = []
        for event in calendarEvents:
            startDateParsed = str(event.startDate).split('-')
            endDateParsed = str(event.endDate).split('-')
            startDate = date(year=int(startDateParsed[0]), month=int(startDateParsed[1]), day=int(startDateParsed[2]))
            endDate = date(year=int(endDateParsed[0]), month=int(endDateParsed[1]), day=int(endDateParsed[2]))

            startTimeParsed = str(event.startTime).split(':')
            endTimeParsed = str(event.endTime).split(':')

            if int(startTimeParsed[0]) > 12:
                startTime = str(int(startTimeParsed[0])-12) + ':' + startTimeParsed[1] + 'pm'
            elif int(startTimeParsed[0]) < 10:
                startTime = startTimeParsed[0][1] + ':' + startTimeParsed[1] + 'am'
            elif int(startTimeParsed[0]) == 11:
                startTime = startTimeParsed[0] + ':' + startTimeParsed[1] + 'am'
            else:
                startTime = startTimeParsed[0] + ':' + startTimeParsed[1] + 'pm'

            if int(endTimeParsed[0]) > 12:
                endTime = str(int(endTimeParsed[0])-12) + ':' + endTimeParsed[1] + 'pm'
            elif int(endTimeParsed[0]) < 10:
                endTime = endTimeParsed[0][1] + ':' + endTimeParsed[1] + 'am'
            elif int(endTimeParsed[0]) == 11:
                endTime = endTimeParsed[0] + ':' + endTimeParsed[1] + 'am'
            else: #endTimeParsed[0] == 12
                endTime = endTimeParsed[0] + ':' + endTimeParsed[1] + 'pm'

            if startDate <= today and endDate >= today:
                events.append({
                    'title': event.title,
                    'startDate': event.startDate,
                    'startTime': startTime,
                    'endDate': event.endDate,
                    'endTime': endTime
                })

        try:
            employeesPerDepartment = totalEmployees/totalDepartments
        except ZeroDivisionError:
            employeesPerDepartment = 0

        sideBarName=current_user.firstName + " " + current_user.lastName
        if len(sideBarName) > 16:
            sideBarName = '...'

        if username == "nicole":
            return render_template('dashboard.html', flag=r"{BRUTE_FORCE_FLAG}", name=current_user.firstName + " " + current_user.lastName, sideBarName=sideBarName, events=events, birthdays=birthdays, username=current_user.username, 
                               phoneNumbers=phoneNumbers, totalEmployees=totalEmployees, totalPayRole=totalPayRole, largestDepartments=largestDepartments, employeesPerDepartment=employeesPerDepartment)
        else:
            return render_template('dashboard.html', name=current_user.firstName + " " + current_user.lastName, sideBarName=sideBarName, events=events, birthdays=birthdays, username=current_user.username, 
                                phoneNumbers=phoneNumbers, totalEmployees=totalEmployees, totalPayRole=totalPayRole, largestDepartments=largestDepartments, employeesPerDepartment=employeesPerDepartment)
    else: #makes it so the user can't put a random string as a username in the URL. eg(http://127.0.0.1:5000/FakeUsername is not acceptable)
        return redirect(url_for('auth.login'))
    
@login_required
@views.route('/<username>/positions')
def positions(username):
    form = PositionForm()

    sideBarName=current_user.firstName + " " + current_user.lastName
    if len(sideBarName) > 16:
        sideBarName = '...'

    return render_template('positions.html', name=current_user.firstName + " " + current_user.lastName, sideBarName=sideBarName, username=username, form=form)

@login_required
@views.route('/<username>/employees')
def employees(username):

    positions = Position.query.filter_by(admin_id=current_user.id).all()
    positionList = []
    for position in positions:
        positionList.append((position.id, position.title))

    departments = Department.query.filter_by(admin_id=current_user.id).all()
    departmentList = []
    for department in departments:
        departmentList.append((department.id, department.title))
    
    form = EmployeeForm()
    form.department.choices = departmentList
    form.position.choices = positionList

    sideBarName=current_user.firstName + " " + current_user.lastName
    if len(sideBarName) > 16:
        sideBarName = '...'

    return render_template('employees.html', name=current_user.firstName + " " + current_user.lastName, sideBarName=sideBarName, username=username, form=form)

@login_required
@views.route('/<username>/departments')
def departments(username):

    form = DepartmentForm()

    sideBarName=current_user.firstName + " " + current_user.lastName
    if len(sideBarName) > 16:
        sideBarName = '...'

    return render_template('departments.html', name=current_user.firstName + " " + current_user.lastName, sideBarName=sideBarName, username=username, form=form)

@login_required
@views.route('<username>/calendar')
def calendar(username):

    # startDateParsed ='2023-12-03'.split('-')
    # endDateParsed ='2024-12-04'.split('-')
    # startDate = datetime(year=int(startDateParsed[0]), month=int(startDateParsed[1]), day=int(startDateParsed[2])).date()
    # endDate = datetime(year=int(endDateParsed[0]), month=int(endDateParsed[1]), day=int(endDateParsed[2])).date()

    # startTime = time(hour=9, minute=21)
    # endTime = time(hour=14, minute=2)


    # new_event = CalendarDates(title='test3', startDate=startDate, startTime=startTime, endDate=endDate, endTime=endTime, frequency=1, admin_id=current_user.id)
    # db.session.add(new_event)
    # db.session.commit()

    form = EventForm()
    editForm = EventFormEdit()

    sideBarName=current_user.firstName + " " + current_user.lastName
    if len(sideBarName) > 16:
        sideBarName = '...'

    return render_template('calendar.html', name=current_user.firstName + " " + current_user.lastName, sideBarName=sideBarName, username=username, form=form, editForm=editForm)

burp_suite/application/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/37379129df.js" crossorigin="anonymous"></script>
    <link rel="icon" href="https://images.vexels.com/media/users/3/157564/isolated/preview/d7d05c7c1070e49a5385019c254901a6-simple-laptop-icon.png">
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/base.css') }}">
    {% block static %} {% endblock %}
    <title id="pageTitle">{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-0 col-xl-2-sm-2 px-0 bg-success">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="{{url_for('views.home')}}" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-3 d-none d-sm-inline" id="squadSync">SquadSync</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item"  class="sidebarLink">
                            <a href="{{url_for('views.dashboard', username=current_user.username)}}" class="nav-link align-middle text-white px-0">
                                <i class="fa-solid fa-house"></i> <span class="ms-1 d-none d-sm-inline" id="dashboardPageLink">Dashboard</span>
                            </a>
                        </li>

                        <li  class="sidebarLink">
                            <a href="{{url_for('views.employees', username=current_user.username)}}" class="nav-link px-0 text-white align-middle">
                                <i class="fa-solid fa-users fa-sm"></i> <span class="ms-1 d-none d-sm-inline" id="employeePageLink">Employees</span></a>
                        </li>

                        <li  class="sidebarLink">
                            <a href="{{url_for('views.positions', username=current_user.username)}}" class="nav-link px-0 text-white align-middle" id="positionsPageLink">
                                <i class="fa-solid fa-briefcase"></i> <span class="ms-1 d-none d-sm-inline">Positions</span></a>
                        </li>
    
                        <li  class="sidebarLink">
                            <a href="{{url_for('views.departments', username=current_user.username)}}" class="nav-link px-0 text-white align-middle">
                                <i class="fa-solid fa-sitemap fa-sm"></i> <span class="ms-1 d-none d-sm-inline" id="departmentsPageLink">Departments</span> </a>
                        </li>

                        <li  class="sidebarLink">
                            <a href="{{url_for('views.calendar', username=current_user.username)}}" class="nav-link px-0 text-white align-middle">
                                <i class="fa-solid fa-calendar-days"></i> </i> <span class="ms-1 d-none d-sm-inline" id="calendarPageLink">Calendar</span> </a>
                        </li>
                    </ul>

                    <div class="dropdown pb-4">
                        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="https://miro.medium.com/v2/resize:fit:500/1*xDIevNE7HEMiJQVTYg0qDQ.png" alt="hugenerd" width="40" height="40" class="rounded-circle">
                            <div class="d-none d-sm-inline mx-1">{{sideBarName}}</div>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                            <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">Logout</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% block content %}

    {% endblock %}

</body>
</html>

burp_suite/application/templates/calendar.html
{% extends 'base.html' %}

{% block static %} 
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/calendar.css') }}">

    <!-- rrule lib -->
    <script src='https://cdn.jsdelivr.net/npm/rrule@2.6.4/dist/es5/rrule.min.js'></script>
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.10/index.global.min.js'></script>
    <!-- the rrule-to-fullcalendar connector. must go AFTER the rrule lib -->
    <script src='https://cdn.jsdelivr.net/npm/@fullcalendar/rrule@6.1.10/index.global.min.js'></script>

    <script type="text/javascript" src="{{ url_for('static',filename='scripts/calendar/calendar-calendar.js') }}" id="calendar-calendar" data-username="{{username}}"></script>
{% endblock %}

{% block title%}Calendar{% endblock %}

{% block content %}
<div class="mainContent">
    <!-- <h1 id="title">Time Off</h1> -->
    
    <div class="calendarContainer">
        <div id='calendar'></div>
    </div>

    <!-- Modal for POST requests -->
    <div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="createModalLabel">Add Event</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                <!-- Modal content goes here -->
                </div>
                <div class="modal-footer">
                    <div class="formContainer">
                        <form action="", novalidate>
                            {{ form.hidden_tag() }}

                            <div class="titleInputContainer">
                                <div><h6 class="formSubtitle">Event Title</h6></div>
                                {{form.title(placeholder='Event Title')}}
                            </div>

                            <div class="startContainer">
                                <div><h6 class="formSubtitle">Event Start</h6></div>
                                <span>{{form.startDate()}}</span>
                                <span>{{form.startTime()}}</span>
                            </div>

                            <div class="clear"></div> <!--Stops position Div from over lapping with the dates -->

                            <div class="endContainer">
                                <div><h6 class="formSubtitle">Event End</h6></div>
                                <span>{{form.endDate()}}</span>
                                <span>{{form.endTime()}}</span>
                            </div>
                            
                            <div class="clear"></div> <!--Stops position Div from over lapping with the dates -->

                            <div class="frequencyContainer">
                                
                                <div>{{form.frequency}}</div>
                            </div>

                            <div class="formButtons">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                {{form.submit()}}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for DELETE and PUT requests -->
    <div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Add Event</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                <!-- Modal content goes here -->
                </div>
                <div class="modal-footer">
                    <div class="formContainer">
                        <form action="", novalidate>
                            {{ editForm.hidden_tag() }}

                            <div class="titleInputContainer">
                                <div><h6 class="formSubtitle">Event Title</h6></div>
                                {{editForm.title(placeholder='Event Title')}}
                            </div>

                            <div class="startContainer">
                                <div><h6 class="formSubtitle">Event Start</h6></div>
                                <span>{{editForm.startDate()}}</span>
                                <span>{{editForm.startTime()}}</span>
                            </div>

                            <div class="clear"></div> <!--Stops position Div from over lapping with the dates -->

                            <div class="endContainer">
                                <div><h6 class="formSubtitle">Event End</h6></div>
                                <span>{{editForm.endDate()}}</span>
                                <span>{{editForm.endTime()}}</span>
                            </div>
                            
                            <div class="clear"></div> <!--Stops position Div from over lapping with the dates -->

                            <div class="frequencyContainer">
                                
                                <div>{{editForm.frequency}}</div>
                            </div>

                            <div class="formButtons">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-danger" id="deleteButton">Delete</button>
                                {{editForm.submit()}}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

burp_suite/application/templates/dashboard.html
{% extends 'base.html' %}

{% block title%}{{name}}'s Dashboard{% endblock %}

{% block static %}
<link rel="stylesheet" href="{{ url_for('static',filename='styles/dashboard.css') }}">

<!-- Script for Chartjs-->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script type="text/javascript" src="{{ url_for('static',filename='scripts/dashboard/dashboard-chart.js') }}" id="dashboard-chart" data-username="{{username}}"></script>
{% endblock %}

{% block content %}

<div class="mainContent">
    <h2 id="title">Hello, {{name}}!</h2>
    
    {% if flag %}
    <div class="flag">
        <strong>Congratulations! Here is your flag:</strong> {{ flag }}
    </div>
    {% endif %}

    <div class="row">
        <div class="col-md-3">
            <div class="summary-box">
                <div class="title"><p>TOTAL EMPLOYEES</p></div>
                <div class="value"><p><span>{{totalEmployees}}</span></p></div>
            </div>
        </div>
    
        <div class="col-md-3">
            <div class="summary-box">
                <div class="title"><p>TOTAL PAY ROLE</p></div>
                <div class="value"><p><span>$ {{totalPayRole}}</span></p></div>
            </div>
        </div>

        <div class="col-md-3">
            <div class="summary-box">
                <div class="title" id="largestDepartmentHeader"><p>LARGEST DEPARTMENT(S)</p></div>
                {% for department in largestDepartments %}
                <div class="value">
                    <div class="largestDepartmentsTitle">
                        {{department.title}} - {{department.employeeCount}} Employees
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="col-md-3">
            <div class="summary-box">
                <div class="title"><p>EMPLOYEES PER DEPARTMENT</p></div>
                <div class="value"><p><span>{{employeesPerDepartment}} / Department</span></p></div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-9">
            <div class="chartsContainer">
                <h4 id="chartTitle">Employees Salaries</h4>
                <canvas id="myChart"></canvas>
            </div>
        </div>
    
        <div class="col-md-3">

            <div class="listBox eventBox">
                <div id="listBoxTitle">TODAY'S CALENDAR</div>
                <div class="list">
                    {% for birthday in birthdays %}
                        <div class="listItemContainer"><i class="fa-solid fa-cake-candles listIcon"></i><p class="listItem">{{birthday.name}}'s Birthday</p></div>
                    {% endfor %}
    
                    {% for event in events %}
                        <div class="listItemContainer"><i class="fa-solid fa-calendar listIcon"></i><p class="listItem">{{event.title}}, {{event.startTime}} - {{event.endTime}}</p></div>
                    {% endfor %}
                </div>
            </div>

            <div class="listBox phoneNumberBox">
                <div id="listBoxTitle">PHONE NUMBERS</div>
                <div class="list">
                    {% for employee in phoneNumbers %}
                        <div class="listItemContainer"><i class="fa-solid fa-phone listIcon"></i><p class="listItem">{{employee.name}}: {{employee.phoneNumber}}</p></div>
                    {% endfor %}
                </div>
            </div>
        </div>
        
    </div>
    <footer id="footer"><p>SquadSync @2023</p></footer>
</div>

{% endblock %}

burp_suite/application/templates/departments.html
{% extends 'base.html' %}

{% block title%}Departments{% endblock %}

{% block static %}
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/departments.css') }}">

    <link href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css" rel="stylesheet" />
    <script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>
    <script type="module" src="{{ url_for('static',filename='scripts/departments/departments-grid.js') }}" id="departments-grid" data-username="{{username}}"></script>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='scripts/departments/departments-chart.js') }}" id="departments-chart" data-username="{{username}}"></script>
{% endblock %}

{% block content %}
<div class="mainContent">
    <h1 id="title">Departments</h1>
  
  <div class="tableContainer">
    <div id="table"></div>
  </div>

  <div class="chartAndFromContainer">
    <div class="formContainer">
      <form action="", novalidate, id="form">
        {{ form.hidden_tag() }}
        <div><h2 id="formTitle">Add Department</h2></div>

        <div id="titleInputDiv">{{form.title(placeholder='Department Title')}}</div>

        <div id="descriptionInputDiv">{{form.description(placeholder='Description')}}</div>

        <div>{{form.submit()}}</div>
      </form>
    </div>

    <div class="chartsContainer">
      <h2 id="chartTitle">Employee Count</h2>
      <canvas id="myChart"></canvas>
    </div>
  </div>

  <footer id="footer"><p>SquadSync @2023</p></footer>

</div>
{% endblock %}

burp_suite/application/templates/index.html
{% extends 'auth/logged_out_base.html' %}

{% block static %}<link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles/index.css') }}">{% endblock %}

{% block title %}Welcome to SquadSync{% endblock %}

{% block content %}

<div id="container">
    <div id="photoContainer">
        <img src="{{ url_for('static',filename='images/homeImage.jpg') }}" alt="Teamwork clipart">
    </div>
    
    <div id="infoContainer">
        <h1 id="squadSync">SquadSync</h1>
        <h5>Effectively lead and manage your team!</h5>

        <div id="regDiv">
            <a href="{{url_for('auth.register')}}" id="regLink">Getting Started? Click Here to Reigster!</a>
        </div>

        <div id="loginDiv">
            <a href="{{url_for('auth.login')}}" id="loginLink">Already Have an Account? Login Here!</a>
        </div>
        
        <div>
            <p id="description">SquadSync is a soultion to all of your employee management needs. Stay on top of your business needs by registering employees and managing their department, role, and 
                salary information. Effectively watch your business grow with a few simple clicks!
            </p>
        </div>
    </div>
</div>

{% endblock %}

burp_suite/application/templates/positions.html
{% extends 'base.html' %}

{% block title %}Positions{% endblock %}

{% block static %} 
    <link href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{{ url_for('static',filename='styles/positions.css') }}">
    <script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>
    <script type="module" src="{{ url_for('static',filename='scripts/positions/positions-grid.js') }}" id="positions-grid" data-username="{{username}}"></script>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='scripts/positions/positions-chart.js') }}" id="positions-chart" data-username="{{username}}"></script>
{% endblock %}

{% block content %}

<div class="mainContent">

  <h1 id="title">Positions</h1>

  <div class="tableContainer">
    <div id="table"></div>
  </div>

  <div class="chartAndFromContainer">
    <div class="formContainer">
      <form action="", novalidate, id="form">
        {{ form.hidden_tag() }}
        
        <div>
          <h2 id="formTitle">Add Position</h2>
        </div>
  
        <div class="titleDiv">
          {{form.title(placeholder='Title')}}
        </div>
  
        <div class="basePayDiv">
          {{form.basePay(placeholder='Base Pay')}}
        </div>
  
        <div class="descriptionDiv">
          {{form.description(placeholder='Description')}}
        </div>
  
        <div class="submitDiv">
          {{form.submit()}}
        </div>
  
      </form>
    </div>
  
    <div class="chartsContainer">
      <h2 id="chartTitle">Base Pay</h2>
      <canvas id="myChart"></canvas>
    </div>

  </div>

  <footer id="footer"><p>SquadSync @2023</p></footer>

</div>
{% endblock %}